project:
  type: book

lang: pt-BR

book:
  title: "Processamento Digital de Imagens"
  subtitle: "Uma abordagem interativa com p5.js"
  author: "Luiz Eduardo da Silva"
  date: today
  chapters:
    - index.qmd
    - chapters/intro.qmd
    - chapters/amostragem.qmd
    - chapters/melhoramento.qmd
    - chapters/fourier.qmd
    - chapters/compressao.qmd
    - chapters/cor.qmd
    - chapters/morfologia.qmd
    - chapters/segmentacao.qmd
    - chapters/representacao.qmd
    - chapters/interpretacao.qmd
    - chapters/opencv.qmd
    - chapters/summary.qmd
    - chapters/references.qmd

bibliography: references.bib

format:
  html:
    css: styles.css
    date-format: "DD/MM/YYYY"
    theme:
      - cosmo
      - brand
  pdf:
    include-in-header:
      text: |
        \usepackage{algorithm}
        \usepackage{algpseudocode}
    pdf-engine: lualatex
    code-block-options:
      fontsize: \small
    documentclass: book
    babel-lang: brazil
